### ISSUE TITLE
Wrong date returned

### ISSUE THREAD

**Issue by LKay** [skratchdot/react-bootstrap-daterangepicker#11]
Looks like something is wrong with returning selected dates. I have a initial date selected and stored in components state just like in the example. I have also `onEvent` callback attached which updates the state. When event `hide` is triggered it returns correct selected dates but just after that the `apply` event is triggered and that one still have `picker` object containing initial dates. So on `hide` event the state is updated to new value and just after that on `apply` event it gets reseted to previous value.

**Comment by skratchdot** [comment]
I vaguely remember an issue like this when I first wrapped the original daterangepicker library.  I believe it was fixed, but might have re-broken (or I might be remembering incorrectly).

I'll try to reproduce this when I get a little time (but not sure when I'll get to it).  Do you have any test code that is published (that exhibits the issue)?  Sounds like it'll be easy for me to reproduce though...

**Comment by peter-mouland** [comment]
I'm not having any problems, so this can probably be closed.  This is how i handle events:
```javascript

  handleEvent(event, picker) {
    if (event.type !== "apply") return;
    this.setState({
      startDate: picker.startDate,
      endDate: picker.endDate
    });
  }
```
