### ISSUE TITLE
React.createClass deprecated now. react-bootstrap-daterangepicker will be incompatible with React 16

### ISSUE THREAD

**Issue by 4refr0nt** [skratchdot/react-bootstrap-daterangepicker#126]
In React 15.5 we have:

> Warning: A Component: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

https://github.com/skratchdot/react-bootstrap-daterangepicker/blob/master/lib/index.js#L15

**Comment by aralroca** [comment]
I have the same Warning! And also this another deprecation:


> Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

**Comment by skratchdot** [comment]
@aralroca - I just published `react-bootstrap-daterangepicker@3.3.0`.  See the changelog: https://github.com/skratchdot/react-bootstrap-daterangepicker/blob/master/CHANGELOG.md

Thanks!
