### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by atkawa7** [skratchdot/react-bootstrap-daterangepicker#132]
Is it possible release a new version? I see the  prop-types and createClass issues have been fixed but npm still has the old version

**Comment by skratchdot** [comment]
Sorry about this. Yes I will try to release this soon.

**Comment by skratchdot** [comment]
@atkawa7 - I just published `react-bootstrap-daterangepicker@3.3.0`.  See the changelog: https://github.com/skratchdot/react-bootstrap-daterangepicker/blob/master/CHANGELOG.md

Thanks!

**Comment by atkawa7** [comment]
@skratchdot Thank you
