### ISSUE TITLE
Can't resolve 'create-react-class' after update to 3.4.0

### ISSUE THREAD

**Issue by barbalex** [skratchdot/react-bootstrap-daterangepicker#134]
I get this error since udating from 3.2.2 to 3.4.0:

    ./~/react-bootstrap-daterangepicker/lib/index.js
    Module not found: Can't resolve 'create-react-class' in 'C:\Users\alex\bb2\node_modules\react-bootstrap-daterangepicker\lib'

**Comment by barbalex** [comment]
also got this while installing:

    react-bootstrap-daterangepicker@3.3.0 requires a peer of create-react-class@>=15.5.0 but none was installed

**Comment by barbalex** [comment]
also happens in 3.3.0 but not in 3.2.2

**Comment by skratchdot** [comment]
@barbalex - Sorry about this.  I merged in some PR's and published new version.  You should be able to fix this by installing all the needed `peerDependencies` in the root of your project:

`npm install --save react react-dom jquery create-react-class prop-types`

I should update the documentation (PR's welcome).
