### ISSUE TITLE
 Cannot find module 'jquery

### ISSUE THREAD

**Issue by sunnybogawat** [skratchdot/react-bootstrap-daterangepicker#143]
I am using daterangepicker in one of my project and when I am running webpack and integrate this build into another project I am always getting following error
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module 'jquery' from 'C:\Users\sunny.bogawat\Workspace\Projects\test_ui_sunny\src\javascript\components\folder'

**Comment by email2vimalraj** [comment]
`jquery` is the peerDependency, hence you will have to install it by yourself: `npm install jquery`.

Please refer point#2 in the [Readme](https://github.com/skratchdot/react-bootstrap-daterangepicker#getting-started)

**Comment by skratchdot** [comment]
@sunnybogawat - I've published a new version with new peer dependency requirements.  Please re-open if you still have issues when using version 4.1.0.  Thanks!
