### ISSUE TITLE
Menu Starts Open

### ISSUE THREAD

**Issue by Smaxor5** [skratchdot/react-bootstrap-daterangepicker#149]
Hi all, so when this component initially renders it has the menu open already and, if clicked on, will stay open forever. If however, I click on the input box it renders properly and dissapears when I click off of it.

Initial Render:
<img width="387" alt="screen shot 2017-08-04 at 11 43 52 am" src="https://user-images.githubusercontent.com/7232185/28976007-361af02a-790a-11e7-9c82-191f566204cd.png">

Afterwards:
<img width="336" alt="screen shot 2017-08-04 at 11 44 13 am" src="https://user-images.githubusercontent.com/7232185/28976019-41b64380-790a-11e7-9be2-afd9b3d472d1.png">

Anyway to stop that from happening?  If it just didn't render open that would solve it.

Thanks!

**Comment by Neeil** [comment]
I just met the same issue.
I use the the picker with React 15 and material-ui. While the drop list always shows at start up.

**Comment by prashand** [comment]
Solved this by including the `css/demo.debug.css` file

**Comment by kvangrae** [comment]
I had the same issue. I did not find `css/demo.debug.css`. However, I solved it by importing [`bootstrap.css v3.3.7`](https://www.npmjs.com/package/bootstrap-css-only).
```css
@import '~bootstrap-css-only/css/bootstrap.css';
```

**Comment by skratchdot** [comment]
Thank you @kvangrae .  I just recently tried to make a few updates to this lib, so it might be easier to add unit tests, and storybook examples.  I'll try to look into this some more and see if there's anything I can do to reproduce this and prevent it.

**Comment by kvangrae** [comment]
Honestly @skratchdot, I don't think this is an issue for `react-bootstrap-daterangepicker`. This should probably be a merge request for [`bootstrap-daterangepicker`](https://github.com/dangrossman/bootstrap-daterangepicker).

Also, IMHO, I feel that [`bootstrap-daterangepicker`](https://github.com/dangrossman/bootstrap-daterangepicker) should remove its dependency on bootstrap since it only uses bootstrap for styling buttons and all other styling are customized in `daterangepicker.css`. Personally, I don't even include `bootstrap.css` because I can override the button styles via the props.

Thank you @skratchdot for maintaining this great library.

**Comment by skratchdot** [comment]
@kvangrae - Good points. I actually wanted to play around w/ adding a transform when I perform the rollup build (like removing all the if/else amd vs cjs vs umd stuff in the `bootstrap-daterangepicker` library- and let rollup handle that).  Perhaps I can look at making some other changes during that "transform phase" (like removing the bootstrap dependency).  Another alternative would be to fork and stop including the source lib, or submit a PR upstream with a bunch of changes.  But that lib has a lot of users, so I'm not sure if it would be good to change a ton of things.

Anyways, thanks for the feedback and kind words!

I should also add some alternative/similar libraries to the readme section of this project.  It's still not a "pure react" project, and I know there are some good react date pickers that were written from scratch.

**Comment by skratchdot** [comment]
Thank you @kvangrae .  I've added updated instructions to the readme here: https://github.com/skratchdot/react-bootstrap-daterangepicker#getting-started

I'll continue adding test cases and stories to the storybook.  Please re-open this issue if there are still issues w/ v4.1.0
