### ISSUE TITLE
daterangepicker.js:13 Uncaught TypeError: Cannot set property 'daterangepicker' of undefined

### ISSUE THREAD

**Issue by wzup** [skratchdot/react-bootstrap-daterangepicker#154]
![datepicker - google chrome 2017-10-03 16 36 36](https://user-images.githubusercontent.com/3880497/31117407-526e22a2-a85c-11e7-9f39-861811a4baa6.png)

![datepicker - google chrome 2017-10-03 16 37 58](https://user-images.githubusercontent.com/3880497/31117413-556d7bd8-a85c-11e7-8eda-355e8ed6fed3.png)

```
    "jquery": "^3.2.1",
    "moment": "^2.18.1",
    "react": "^15.5.4",
    "react-bootstrap": "^0.31.2",
    "react-bootstrap-daterangepicker": "^3.4.1",
    "webpack": "^2.2.1"
```

**Comment by skratchdot** [comment]
Can you please re-try w/ version 4.1.0?  There are updated instructions in the readme.  Feel free to re-open this ticket if there are still issues.
