### ISSUE TITLE
support for react 16

### ISSUE THREAD

**Issue by foodaka** [skratchdot/react-bootstrap-daterangepicker#157]
On react version 16.0.0 on gettting warnings in the console. any ideas how to remove?

Warning: Failed prop type: Invalid prop `startDate` supplied to `<<anonymous>>`.

**Comment by UX-Unicorn** [comment]
I had this issue and changed the format of how I sent the dates in to just a moment() and it went it fixed it.

**Comment by skratchdot** [comment]
I just added a story for initializing `startDate` with a moment instance, and I don't see this warning:
https://github.com/skratchdot/react-bootstrap-daterangepicker/commit/6ce8ce4471c9b62ea9a6d7874d6f94a353766109

View story: https://projects.skratchdot.com/react-bootstrap-daterangepicker/?knob-label=click%20to%20open&knob-startDate=1%2F1%2F2017&knob-endDate=1%2F5%2F2017&selectedKind=DateRangePicker&selectedStory=with%20start%20and%20end%20date&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook%2Factions%2Factions-panel

I don't see anything an the console.  Please re-open if you still experience this issue w/ version 4.1.0.

Thanks!
