### ISSUE TITLE
showCustomRangeLabel = false does not seem to be working.

### ISSUE THREAD

**Issue by chiku80** [skratchdot/react-bootstrap-daterangepicker#159]
First of thank you so much for this component. its helped me out a lot. I am trying to hide the custom label calendar selection via the showCustomRangeLabel property. However, this does not seem to do the trick. I still see the custom range label on the front end. Following the snippet i am using:
```
return (
  		<DateRangePicker
                  showCustomRangeLabel="false"
                  startDate={this.state.startDate}
                  endDate={this.state.endDate}
                  ranges={this.state.ranges}
                  onEvent={this.handleEvent}
                  buttonClasses="btn btn-sm">
  					<Button className="selected-date-range-btn" bsSize="xsmall">
  						<div className="pull-left"><Glyphicon glyph="calendar" /></div>
  						<div className="pull-right">
  							<span>
  								{label}
  							</span>
  							<span className="caret"></span>
  						</div>
  					</Button>
  				</DateRangePicker>
    		);
```
I apologize in advance if this a known issue. I did a search and came up with nothing.

**Comment by skratchdot** [comment]
Does `showCustomRangeLabel={false}` work? (notice `"false"` vs `{false}`)

**Comment by chiku80** [comment]
the {false} worked! I feel embarrassed.  I should have tried that...
Thankyou so much!

**Comment by skratchdot** [comment]
No worries! Glad it ended up working.
