### ISSUE TITLE
Module not found: Can't resolve 'bootstrap-daterangepicker'

### ISSUE THREAD

**Issue by vijaygawade18** [skratchdot/react-bootstrap-daterangepicker#169]
Hi @skratchdot I am having this issue while implementing the date-picker in my app.

`import DateRangePicker from 'react-bootstrap-daterangepicker';`

```
./node_modules/react-bootstrap-daterangepicker/dist/bundle.js,
Module not found: Can't resolve 'bootstrap-daterangepicker'
```

Need your help to resolve it.

**Comment by skratchdot** [comment]
@vijaygawade18 - It looks like the peerDependencies aren't satisfied.  Can you try running:

```
npm install --save bootstrap-daterangepicker react jquery moment prop-types
```

and see if it fixes your issue?

**Comment by vijaygawade18** [comment]
Hi @skratchdot issue is resolved. I had not imported the `bootstrap-daterangepicker`  in my component file. Importing it solved my problem. 
Thanks!

**Comment by sr3d** [comment]
For Rails 5 users, make sure you add both packages, e.g.

`yarn add bootstrap-daterangepicker react-bootstrap-daterangepicker`

otherwise you'll get similar complaint.

**Comment by Lamanris** [comment]
> For Rails 5 users, make sure you add both packages, e.g.
> 
> `yarn add bootstrap-daterangepicker react-bootstrap-daterangepicker`
> 
> otherwise you'll get similar complaint.

Thank you! It helped me
