### ISSUE TITLE
endDate dose not work.

### ISSUE THREAD

**Issue by KaiOrange** [skratchdot/react-bootstrap-daterangepicker#184]
When I use setState update the endDate.I find it doesn't work.
You can see this picture the input box of endDate is right,but  the endDate of the selection box below has not changed.
![endDate dose not work](https://user-images.githubusercontent.com/24317428/43761966-3be54368-9a59-11e8-817e-3ae17ab278fa.png)

**Comment by skratchdot** [comment]
I've published a new version 6.0.0 and the API has changed.  Please see the updated examples;
https://projects.skratchdot.com/react-bootstrap-daterangepicker/

You need to treat this component as an "uncontrolled component" now.
