### ISSUE TITLE
Compatible w/ bootstrap-daterangepicker >= 3.0.2?

### ISSUE THREAD

**Issue by swrobel** [skratchdot/react-bootstrap-daterangepicker#188]
It seems a [pretty significant change](https://github.com/dangrossman/daterangepicker/commit/6908f9b1a9f873d79acab276b69065ad0f948dc0) was made to the css (amongst others)

**Comment by skratchdot** [comment]
Thank you!  I'm just now seeing this.  I will try to look into it tonight.

**Comment by skratchdot** [comment]
Sorry for the delay on this.  The latest version is compatible with daterangepicker@3.1.0:
https://github.com/skratchdot/react-bootstrap-daterangepicker/blob/66622f9752dcd98bd7a6543f77d9c1e84352cd10/package.json#L59

View the latest storybook:
http://projects.skratchdot.com/react-bootstrap-daterangepicker/
