### ISSUE TITLE
How can I pass dynamic locale for dateRangePicker When I use 'moment/min/locales' working instead of moment

### ISSUE THREAD

**Issue by srivathsa-kavirayuni** [skratchdot/react-bootstrap-daterangepicker#196]
How can I pass locales dynamically to DateRangePicker to get those formats where as I'm using `moment/min/locales`  for locale changing. when I import 'moment' and trying to change moment.locale() it is not working. So is there any way to change the locale in DateRangePicker.
Here is my code 
`<DateRangePicker
      startDate={this.props.startDate}
      endDate={this.props.endDate}
      maxDate={moment()}
      ranges={config(this.props.l)}
      onEvent={this.handleEvent}
      opens="left"
      locale={{
        format: dateFormatBasedOnCountry[this.props.langCode.toUpperCase()],
        cancelLabel: this.props.l('Cancel'),
        applyLabel: this.props.l('Apply'),
        customRangeLabel: this.props.l('Custom Range'),
      }}
   key={this.state.isTransChanged ? `date-range-picker-${this.state.index++}` : undefined} // added key to remount
      // the component for translations
    >`

**Comment by Algo87** [comment]
Maybe it will be useful for someone

If you need to set local dynemic in react-bootstrap-daterangepicker you can set it in initialSettings.locale like this
const [lang, setLang] = useState(getCookie(authConstants.language) || "en");
 initialSettings={{
        startDate: period[0], endDate: period[1],
        locale: {
          locale: moment.locale(lang), // lang 
          cancelLabel: t("cancel"),
          applyLabel: t("apply"),
          format: "DD.MM.YYYY"
        },
      }}
