### ISSUE TITLE
singleDatePicker shows range of dates when date is changed dynamically

### ISSUE THREAD

**Issue by dushyantbangal** [skratchdot/react-bootstrap-daterangepicker#211]
I have a single date picker:

```
<DateRangePicker
    singleDatePicker={true}
    startDate={this.state.startDate}
    minDate='01/01/2012'
    maxDate={this.state.maxDate}
    showWeekNumbers={false}
    open={'left'}
    showDropdowns={true}
    onApply={this.handleCustomDate}>
    
    <button className="date-ranger"><i className="glyphicon glyphicon-calendar"></i>{" "+ moment(this.state.startDate).format('DD-MMM-YYYY')} <b className="caret"></b></button>
</DateRangePicker>
```

When I change the date on it dynamically, without selecting from the date picker, the date on the button gets changed.
However, when I click on the picker again, it shows as if multiple dates have been selected, to and from the old date and the new date I set dynamically.

**Steps to reproduce:**
1. Render the date picker as shown above
2. Put the following in your `componentDidMount`:

```
let newDate = new Date();
newDate.setDate(newDate.getDate()-10);

setTimeout(()=> this.setState({startDate:newDate}),10000);
```
3. Open the page
4. Wait for 10 seconds
5. Click on the picker
You will see it shows 10 days selected from current date.

**On page load:**
![image](https://user-images.githubusercontent.com/13764676/69217634-21017e00-0b95-11ea-82ce-cacc07a0c7a0.png)

**After changing via state:**
![image](https://user-images.githubusercontent.com/13764676/69217672-2ced4000-0b95-11ea-9f56-eea32566e39b.png)

**Comment by skratchdot** [comment]
I've published a new version 6.0.0 and the API has changed.  Please see the updated examples;
https://projects.skratchdot.com/react-bootstrap-daterangepicker/

You need to treat this component as an "uncontrolled component" now.
