### ISSUE TITLE
Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps

### ISSUE THREAD

**Issue by leonardodominik801** [skratchdot/react-bootstrap-daterangepicker#214]
`componentWillReceiveProps` has been renamed, and is not recommended for use. 

See https://fb.me/react-unsafe-component-lifecycles for details. 

In React 17.x, only the UNSAFE_ name will work.

**Comment by psaruks** [comment]
upvote

**Comment by Roeefl** [comment]
Joining this request, please

**Comment by simdad19** [comment]
Seems like no one is maintaining this library

**Comment by ColdTuna** [comment]
Trying to patch this here, do I change the bundle.js only or do I change the src and rebuild the package?

It's unfortunate that this great wrapper is unmaintained.

**Comment by ColdTuna** [comment]
Got it! I just had to change lines 150 and 151 in `dist/bundle.js` from `componentWillReceiveProps` to `UNSAFE_componentWillReceiveProps` and the warning disapeared.

**Comment by Roeefl** [comment]
@ColdTuna Thanks you're a gem =D

**Comment by skratchdot** [comment]
This has finally been fixed in v5.0.1
