### ISSUE TITLE
Updating `ranges` prop does not update the date ranger picker UI

### ISSUE THREAD

**Issue by rehanumar** [skratchdot/react-bootstrap-daterangepicker#215]
I am updating the ranges prop with latest props object from store but in UI initial props object is displayed. So my hypothesis is that updating the ranges props does not sync with UI.
I have debugged this through the React Dev Tool and DateRangePicker component have latest props in the format mentioned in [http://www.daterangepicker.com/#example4](http://www.daterangepicker.com/#example4).

```
<DateRangePicker
                startDate={moment(startDate)}
                endDate={moment(endDate)}
                maxDate={moment()}
                ranges={dateRanges}
                autoApply={true}
                opens="left"
                onApply={this.onApplyHandler}
              >
```

where old value of `dateRanges={'Activity1': [moment(StartDate), moment(EndDate)]}`
and new value of ``dateRanges={'Activity2': [moment(StartDate), moment(EndDate)]}``

**Comment by rehanumar** [comment]
@skratchdot and others, following is the link to fix of this issue.
https://github.com/skratchdot/react-bootstrap-daterangepicker/pull/216

**Comment by vidhi6891** [comment]
Hello, is the above PR merged ? I am facing the same issue wherein the calendar is not re-re dering on a change in the ranges prop

**Comment by skratchdot** [comment]
Please see this comment on how to change props like "range":

https://github.com/skratchdot/react-bootstrap-daterangepicker/pull/216#issuecomment-663299357

The only props you should treat as "controlled props" are startDate and endDate.  All others should be treated as "initial" values only.  I will try to release a new version (v6) with a completely changed api to make this more clear (and some better examples)
