### ISSUE TITLE
Module '"react-bootstrap-daterangepicker"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

### ISSUE THREAD

**Issue by temurih** [skratchdot/react-bootstrap-daterangepicker#220]
I am not sure what this mean?

![image](https://user-images.githubusercontent.com/3893769/81840103-b9097000-9505-11ea-9af2-eafb69a542f6.png)

**Comment by skratchdot** [comment]
It looks like you are using typescript, so you probably need to:

```
import * as DateRangePicker from 'react-bootstrap-daterangepicker'
```

I haven't used typescript for a while, but please re-open if that does not fix the issue for you. Thanks!
