### ISSUE TITLE
Event onApply not working with version bootstrap-daterangepicker 3.1.0

### ISSUE THREAD

**Issue by arisvn-truongNQ** [skratchdot/react-bootstrap-daterangepicker#222]
`
    "bootstrap-daterangepicker": {
      "version": "3.1.0",
      "resolved": "https://registry.npmjs.org/bootstrap-daterangepicker/-/bootstrap-daterangepicker-3.1.0.tgz",
      "integrity": "sha512-oaQZx6ZBDo/dZNyXGVi2rx5GmFXThyQLAxdtIqjtLlYVaQUfQALl5JZMJJZzyDIX7blfy4ppZPAJ10g8Ma4d/g==",
      "requires": {
        "jquery": ">=1.10",
        "moment": "^2.9.0"
      }
    },
`
![image](https://user-images.githubusercontent.com/46480134/84645244-7b479f00-af2a-11ea-946f-5515d685fe4f.png)

When I remove file package-lock.json and install again, event onApply not working.

**Comment by skratchdot** [comment]
I believe this is working as intended in v5.0.1.  If you click on the first item in the range, it "de-selects" the startDate, and the apply button is disabled.  Feel free to re-open if you encounter an issue.
