### ISSUE TITLE
Date range picker input box doesn't show up calendar icon ?

### ISSUE THREAD

**Issue by pradeepn541** [skratchdot/react-bootstrap-daterangepicker#229]

**Comment by skratchdot** [comment]
Bootstrap 4 no longer includes icons by default.

You can style your input however you want via css, so you can pick one of the following icon sets to get a calendar icon:
https://getbootstrap.com/docs/4.5/extend/icons/

**Comment by Daniel-Raz-Supersmart** [comment]
> Bootstrap 4 no longer includes icons by default.
> 
> You can style your input however you want via css, so you can pick one of the following icon sets to get a calendar icon: https://getbootstrap.com/docs/4.5/extend/icons/

and how can I add this icon to the input field?

**Comment by skratchdot** [comment]
> 
> and how can I add this icon to the input field?

try this:
https://stackoverflow.com/a/61233816
