### ISSUE TITLE
How to set max date

### ISSUE THREAD

**Issue by rafioktavian** [skratchdot/react-bootstrap-daterangepicker#233]
I have code 

```
 const maxDateValue = new Date().toISOString();
<DateRangePicker
  maxDate={maxDateValue}
  autoUpdateInput={true}
  startDate={startDate}
  endDate={endDate}
  locale={{ format: "YYYY-MM-DD" }} 
  onApply={onChangeDate}>
  <input type="text" className="form-control" value={labelDate} onChange={onChangeDate} />
</DateRangePicker>
```

how the solution to this problem?

**Comment by lambdatechdev** [comment]
this is the wrapper package for bootstrap-daterangepicker while the main library has this option but the wrapper package doesn't added this specific option. After going through the library code I've added the option after inherit the library with with my custom class. here's the code example for this.
```
import DateRangePicker from "react-bootstrap-daterangepicker";

class CustomDateRangePicker extends DateRangePicker {
    constructor(props) {
        super(props);
        this.options.push("maxSpan");
    }
}

export default CustomDateRangePicker;
```
now you can use <CustomDateRangePicker/> and pass all all the props you want to.
eg in your case:
```const maxDateValue = new Date().toISOString();
<CustomDateRangePicker
  maxDate={maxDateValue}
  autoUpdateInput={true}
  startDate={startDate}
  endDate={endDate}
  locale={{ format: "YYYY-MM-DD" }} 
  onApply={onChangeDate}>
  <input type="text" className="form-control" value={labelDate} onChange={onChangeDate} />
</DateRangePicker>
```

**Comment by omerkhan8** [comment]
this is the wrapper package for bootstrap-daterangepicker while the main library has this option but the wrapper package doesn't added this specific option. After going through the library code I've added the option after inherit the library with with my custom class. here's the code example for this.
```
import DateRangePicker from "react-bootstrap-daterangepicker";

class CustomDateRangePicker extends DateRangePicker {
    constructor(props) {
        super(props);
        this.options.push("maxSpan");
    }
}

export default CustomDateRangePicker;
```
now you can use <CustomDateRangePicker/> and pass all all the props you want to.
eg in your case:
```const maxDateValue = new Date().toISOString();
<CustomDateRangePicker
  maxDate={maxDateValue}
  autoUpdateInput={true}
  startDate={startDate}
  endDate={endDate}
  locale={{ format: "YYYY-MM-DD" }} 
  onApply={onChangeDate}>
  <input type="text" className="form-control" value={labelDate} onChange={onChangeDate} />
</DateRangePicker>
```

**Comment by skratchdot** [comment]
You need to change your code to use the `initialSettings` prop.  You also need to use this component as an "uncontrolled" component:
https://github.com/skratchdot/react-bootstrap-daterangepicker/#documentation
