### ISSUE TITLE
Get name of predefined range as a prop

### ISSUE THREAD

**Issue by usahai** [skratchdot/react-bootstrap-daterangepicker#236]
I'd like to use the label in the predefined ranges to replace the label in my button component. Is there any way to extract that from the component? I looked through the event props of the onApply component, but there is nothing in there. Also looked through the Button callback, nothing there either.

**Comment by usahai** [comment]
![image](https://user-images.githubusercontent.com/2849176/122345333-51301f00-cf7a-11eb-8750-f6c71ee435ee.png)
So when I click on this month, it would be nice if I could change the label to "this month" as well

**Comment by Haowjy** [comment]
you can listen to `onCallback` for `callback(start, end, label),` and the `label` is the label of the predefined range.

**Comment by usahai** [comment]
It worked! Thanks!!
