### ISSUE TITLE
Small housekeeping items? (Documentation and console.log)

### ISSUE THREAD

**Issue by philberry-bb** [skratchdot/react-bootstrap-daterangepicker#25]
Love the component.  Two small things:

#### Documentation Update

The readme usage says to use the following:
* &lt;DateRangePicker startDate="1/1/2014" endDate="3/1/2014">

I found I had to use this instead:
*  &lt;DateRangePicker startDate={moment("2014-04-23T09:54:51")} endDate={moment("2014-08-23T09:54:51")}>

#### Index.js Has The Following Line
* console.log(this.$picker.data('daterangepicker'));

Was that perhaps left over from development?

**Comment by skratchdot** [comment]
Yes. Sorry about the console.log(). Not sure how that got in there. Definitely a mistake.

**Comment by skratchdot** [comment]
I updated the README w/ the correct moment() documentation. Thanks for that!
