### ISSUE TITLE
Uncaught TypeError: Cannot set property 'daterangepicker' of undefined

### ISSUE THREAD

**Issue by rkhayat** [skratchdot/react-bootstrap-daterangepicker#34]
The following line in daterangepicker.js causing an error.
```
   root.daterangepicker = factory(root, exports, momentjs, $);
```

My component looks like this
```
var React = require('react');
var moment = require('moment');
var $ = require('jquery');
var DateRangePicker = require('react-bootstrap-daterangepicker');
var CustomDatePickerComponent = React.createClass({
    render: function () {
        return (
        	<div>
       		<DateRangePicker startDate={moment('1/1/2014')} endDate={moment('3/1/2014')}>
                <div>Click Me To Open Picker!</div>
            </DateRangePicker>
        	</div>
        );
    }
});
module.exports = CustomDatePickerComponent;
```

**Comment by skratchdot** [comment]
Can you tell me which versions of React, moment, jQuery, and react-bootstrap-daterangepicker you have installed locally?

I wrote a tool called npm-dview that can show you this data `npm install -g npm-dview` then run: `npm-dview` from within your project.  You can also use `npm-shrinkwrap` and probably another easier way that I'm not thinking of...

Also, I'm going to publish a new version soon that works w/ React v0.14.0, so I'll be recommending that everyone use specific versions of this library (based on what versions of jQuery, React, etc they are using)...

**Comment by rkhayat** [comment]
@skratchdot Thanks for the reply!

Based on package.json...
```
"react": "^0.13.3",
"jquery": "^2.1.4",
"react-bootstrap-daterangepicker": "^0.4.0",
```

**Comment by peter-mouland** [comment]
this will be fixed with https://github.com/dangrossman/bootstrap-daterangepicker/pull/817

**Comment by peter-mouland** [comment]
fyi, The above PR has been merged and just waiting for a new release

**Comment by skratchdot** [comment]
Ok. I just published a new version to npm: `1.0.0-beta.2`

This should be fixed by commit d2c90282b8606102d4c106ead561108585dc3c65

**Comment by peter-mouland** [comment]
sorry - I wasn't clear enough. I was waiting for a new release from bootstrap-daterangepicker.  This has been done now and v2.0.13 is out :)

**Comment by wzup** [comment]
So how to fix this

https://github.com/skratchdot/react-bootstrap-daterangepicker/issues/43#issuecomment-333777215
