### ISSUE TITLE
dependency not included as a dependency!!

### ISSUE THREAD

**Issue by peter-mouland** [skratchdot/react-bootstrap-daterangepicker#36]
I see this uses the great code from https://github.com/dangrossman/bootstrap-daterangepicker
except you do not have it as a dependency!

You should really remove the code from your lib folder and include it within your package.json

**Comment by skratchdot** [comment]
@peter-mouland - Hey, a few people have asked about this.  Here's one comment I made: https://github.com/skratchdot/react-bootstrap-daterangepicker/pull/9#issuecomment-69480623 about why I originally didn't add it as a dependency.

The 2nd time I looked into it, dangrossman wasn't the published author in npm (and the published version on npm was a few versions behind the version I was using in this lib).

It looks like @dangrossman is now the published author (https://www.npmjs.com/~dangrossman) and the published version seems to be up-to-date (https://www.npmjs.com/package/bootstrap-daterangepicker);

I should now be able to start depending on the npm version and stop using the `gulp download` script I was relying on.

One thing I did notice from `npm view bootstrap-daterangepicker`:

```
{ name: 'bootstrap-daterangepicker',
  time:
   { modified: '2015-09-17T03:02:25.892Z',
     created: '2015-06-04T12:22:42.292Z',
     '1.3.21': '2015-06-04T12:22:42.292Z',
     '1.3.2-1.0': '2015-06-04T12:30:38.118Z',
     '1.3.21-npm': '2015-06-05T06:55:21.876Z',
     '1.3.21-npm.1': '2015-06-05T06:59:03.588Z',
     '1.3.21-2': '2015-06-05T07:00:55.599Z',
     '1.3.2-1.1': '2015-06-05T07:02:14.939Z',
     '2.0.6': '2015-08-03T12:06:02.362Z',
     '2.0.9': '2015-09-10T03:36:53.253Z',
     '2.0.11': '2015-09-17T03:02:25.892Z' },
  maintainers:
   [ 'g0blin <seidrhrafn@gmail.com>',
     'vperron <victor@iso3103.net>',
     'dangrossman <dan@dangrossman.info>' ],
  'dist-tags': { latest: '2.0.11' },
  description: 'Date range picker component for Bootstrap',
  versions: [ '1.3.2-1.1', '2.0.6', '2.0.9', '2.0.11' ],
  homepage: 'https://github.com/dangrossman/bootstrap-daterangepicker',
  repository:
   { type: 'git',
     url: 'https://github.com/dangrossman/bootstrap-daterangepicker.git' },
  author: 'Dan Grossman <dan@dangrossman.info> (http://www.dangrossman.info)',
  bugs: { url: 'https://github.com/dangrossman/bootstrap-daterangepicker/issues' },
  license: 'MIT',
  readmeFilename: 'README.md',
  version: '2.0.11',
  main: 'daterangepicker.js',
  style: 'daterangepicker.css',
  scripts: { test: 'echo "Error: no test specified" && exit 1' },
  dependencies: { jquery: '^1.10', moment: '^2.9.0' },
  gitHead: '385be8226bf3d403af3942e06a90e18dc01344fc',
  dist:
   { shasum: '299a2181e1f41d0fb4c340d209d159c2f0766ea7',
     tarball: 'http://registry.npmjs.org/bootstrap-daterangepicker/-/bootstrap-daterangepicker-2.0.11.tgz' },
  directories: {} }
```

Not every version is getting published.  Sometimes people will log a bug here, and I can `gulp download` and `npm publish` to fix the issue for them.  If I add the lib as a dependency, I won't always be able to do that (and will need to wait for one of the upstream maintainers to do an npm publish)...

**Comment by peter-mouland** [comment]
yeah, that is true - but that is how dependencies work.  Any bugs should be reported to the source and referenced here. You can keep your workload down by looking after your own house, then helping out your neighbor with PR's.

How many of your bug fixes did you push to the owner of the lib?

handy little wrapper all the same though.  I'm after one that doesn't rely on jQuery so i can make it isomorphic... looks like i might have to fork Dan's code then fork this wrapper!

**Comment by skratchdot** [comment]
Yeah... I would definitely like to make this follow the principles of React a little better.  It started as a quick hack for a project that I figured would help other people.  I just published a new version using `gulp update` so we are now on the latest upstream.

I'll pull in the React v0.14.0 pull request that someone else submitted, and start depending on the npm version of `bootstrap-daterangepicker` (to close this bug out).  Then I'm going to start depending on the latest npm versions of react, bootstrap-react, and bootstrap-daterangepicker.

People that use this lib will have to start using the proper version I guess :)

I'll try to publish a changelog or something and update my documentation (which sucks).

**Comment by skratchdot** [comment]
Also, to answer your question about my bugfixes: I didn't push many upstream because not many were needed.  I submitted a few before there was a package.json file, and worked on some to make it node ready, but can't remember if there were already open PR's doing similar things.  I've also requested a few people that submit PR's here, to submit them upstream instead, so I think a few of those have made it in....

**Comment by peter-mouland** [comment]
cool - a worthwhile update. that's what version numbers are therefore so people should understand. Especially as its a step closer to standard/expected approaches

**Comment by joshhornby** [comment]
Big +1 from me on this.
