### ISSUE TITLE
Uncaught Error: Cannot find module 'react-bootstrap-daterangepicker'

### ISSUE THREAD

**Issue by wzup** [skratchdot/react-bootstrap-daterangepicker#55]
Fist, installation is finished with this warn: `npm WARN install: UNMET PEER DEPENDENCY`:
```
$ npm install --save react-bootstrap-daterangepicker
npm WARN install Couldn't install optional dependency: Unsupported
moment@2.10.6 node_modules\moment -> node_modules\bootstrap-daterangepicker\node_modules\moment
app@0.0.0 c:\Users\user\sbox\node\app
├── UNMET PEER DEPENDENCY jquery@2.1.4
└── react-bootstrap-daterangepicker@1.0.6

npm WARN EPEERINVALID react-bootstrap-daterangepicker@1.0.6 requires a peer of jquery@^1.11.3 but none was installed.
```

Then, after installation and `require`-ing `react-bootstrap-daterangepicker` in a module with my app's components, an error was thrown in a browser console:
`Uncaught Error: Cannot find module 'react-bootstrap-daterangepicker'`

My components are compiled with Browserify all right without `react-bootstrap-daterangepicker`. So it is not a build issue.

Why this error? How to solve it?

Versions of packages in my `package.json`
```
    "jquery": "^2.1.4",
    "moment": "^2.10.6",
    "react": "^0.14.3"
```

**Comment by wzup** [comment]
Delete it, pls.

**Comment by skratchdot** [comment]
I think all we can do is close it.  You can edit your comments if you want, but it looks like that's all we can do.
