### ISSUE TITLE
Missing alwaysShowCalendars in ./lib/get-options.js

### ISSUE THREAD

**Issue by carlsagan21** [skratchdot/react-bootstrap-daterangepicker#62]
I tried to appy an option called 'alwaysShowCalendars'. It supposed to work exactly what it is called - when range option is applied, to make calendar visible.

But in react-bootstrap-daterangepicker the option was not working. So I changed './lib/get-options.js' to recognize it, and it worked perfectly.

So plz check, and I'm gonna make a pull request.

**Comment by skratchdot** [comment]
Ok. I pulled in your change. The way that file is generated is by running `gulp get-options`

**Comment by carlsagan21** [comment]
thx ;)
