### ISSUE TITLE
React v15.0 no longer support React.__spread

### ISSUE THREAD

**Issue by carlsagan21** [skratchdot/react-bootstrap-daterangepicker#71]
#happens 
index.js:83 Uncaught TypeError: React.__spread is not a function

I guess it's because of React version up.
There was a major version up to v15.0. plz check.
https://facebook.github.io/react/blog/

**Comment by carlsagan21** [comment]
check this also.
offical solution from reactjs

https://github.com/reactjs/core-notes/issues/6#event-620063175

**Comment by skratchdot** [comment]
@carlsagan21 - thanks for this. I'll push a fix today.

**Comment by carlsagan21** [comment]
Actually react 15.0.1 decided to temporary support React.__spread, but with warning.

**Comment by skratchdot** [comment]
fixed in commit 0498756b0df1d741fd6c3e19b71202da045a0552  I published 3.0.0 which can be used with React 15.  Thanks for checking it out!

**Comment by skratchdot** [comment]
Oh. dang.  Well, I already submitted a change that *should* work, but I don't like requiring on `object-assign`.  That's just a temporary fix until I create a "src" folder w/ JSX that transpiles to the "lib" folder...

**Comment by carlsagan21** [comment]
Well.. You can check how Babel solve this. object.assign is compiled something like 'var _extend = Object.assign || {long function with for loop which i cannot remember}'
Its quite reasonable I think.
