### ISSUE TITLE
Release new version and update package on npm

### ISSUE THREAD

**Issue by kibin** [skratchdot/react-bootstrap-daterangepicker#78]
It seems like there were some commits with fixes since version 3.0.0, maybe it’s time to release 3.0.1 with those fixes?

**Comment by skratchdot** [comment]
Good point. I'll build a new version and publish it...

**Comment by skratchdot** [comment]
Fixed with commit eedc6c52370d53da6d0b885e4d6410989eec9aa5

**Comment by skratchdot** [comment]
I've published `3.1.0`: https://www.npmjs.com/package/react-bootstrap-daterangepicker
