### ISSUE TITLE
v2.1.0

### ISSUE THREAD

**Issue by Mistereo** [skratchdot/react-bootstrap-daterangepicker#92]
`v2.1.0` has invalid semver ranges for `react` and `react-dom`: ">=0.14.0|>=15.0.0" -> ">=0.14.0||>=15.0.0".

**Comment by nvkudva** [comment]
Yes. Same issue we too are facing. 
https://github.com/skratchdot/react-bootstrap-daterangepicker/commit/7310827e1fda65629bb1536633ff7ee1dedd5b3f

We used previous 2.0.0 version to get around this for now.

**Comment by skratchdot** [comment]
@Mistereo / @nvkudva - geez.  I'm just now seeing this. Sorry.  I'll publish a fix shortly.

**Comment by skratchdot** [comment]
Well, I published 2.2.0 which contains 91ca770d72df384d5f097117aa8d8c092d2c08e8.  Hopefully that fixes the issue.

**Comment by nvkudva** [comment]
Awesome.Thanks a lot. Just thought.. I think it should have been published as a patch version .. as 2.1.1 so that if someone is importing it with ~2.1.x. or ^2.1.x it would just work. Probably may not be a big deal as people may not be even using 2.1.0 anyway as it would break.

**Comment by skratchdot** [comment]
@nvkudva - yes that makes a lot of sense.  This lib def isn't following semver (and is kind of a mess) ;)

I plan on making a new major version for each new major version of React.  I'll try to start following semver better with the minor and patch versions

**Comment by skratchdot** [comment]
Ok. Publish 2.1.1 as well: https://github.com/skratchdot/react-bootstrap-daterangepicker/releases/tag/2.1.1
